fix the following Flake8 errors: nii/rmgroups.py:68:20: E741 ambiguous variable name 'l' nii/rmgroups.py:68:31: E741 ambiguous variable name 'l' nii/rmgroups.py:81:5: F811 redefinition of unused '__init__' from line 38 nii/rmgroups.py:102:20: E741 ambiguous variable name 'l' nii/rmgroups.py:102:31: E741 ambiguous variable name 'l' nii/rmgroups.py:190:17: F841 local variable 'map_group' is assigned to but never used nii/rmgroups.py:292:1: W391 blank line at end of file