Allow read-write users to remove linked  [OSF-440]
* Allow read-write users to remove linked nodes

Exception: if the RW user does not have permission to see the linked node, do not show delete controls. (It would be hard to figure out what they were deleting!)

[#OSF-440]

* Allow deletion of pointers, even if user doesn't know what they are deleting

* Opportunistic import cleanup

Remove unused imports and sort

* Remove duplicate unit test

And other opportunistic syntax cleanup

* Basic tests for whether deletion controls are present

* Improve test

Make sure that nodes are present, in addition to checking that controls are not